// Hebrew (עברית): merges every segment into the flat dictionary that
// royaleI18n.ts imports. Generated by the i18n parallel-work restructure.
// Keep new keys in their matching segment file (core, board, cinema, arena,
// onboarding, docs, pages, chat, misc), not here.
//
// QUALITY: machine-assisted single-pass translation (codex worker, 2026-07-31),
// glossary-enforced; flagged for native-speaker review.
import core from "./core";
import board from "./board";
import cinema from "./cinema";
import arena from "./arena";
import onboarding from "./onboarding";
import docs from "./docs";
import pages from "./pages";
import chat from "./chat";
import misc from "./misc";

export const he: Record<string, string> = {
  ...core,
  ...board,
  ...cinema,
  ...arena,
  ...onboarding,
  ...docs,
  ...pages,
  ...chat,
  ...misc,
};
