// Indonesian (Bahasa Indonesia): merges every segment into the flat
// dictionary that royaleI18n.ts imports. Generated by the i18n parallel-work
// restructure so 8 agents can each own one segment file per locale without
// touching a shared file. This file should not need to change again: add
// new keys to the relevant segment file instead (core, board, cinema, arena,
// onboarding, docs, pages, chat, misc).
import core from "./core";
import board from "./board";
import cinema from "./cinema";
import arena from "./arena";
import onboarding from "./onboarding";
import docs from "./docs";
import pages from "./pages";
import chat from "./chat";
import misc from "./misc";

export const id: Record<string, string> = {
  ...core,
  ...board,
  ...cinema,
  ...arena,
  ...onboarding,
  ...docs,
  ...pages,
  ...chat,
  ...misc,
};
