// Chinese, Traditional (繁體中文): merges every segment into the flat dictionary that
// zh-Hant BASE: converted from this repo's zh-Hans segment with OpenCC
// (cn->twp: Taiwan phrase conventions, 軟體/資訊/網路/預設/影片/伺服器...)
// plus a manual Taiwan-usage pass (帳 not 賬, 台 not 臺, 綁定, 分頁, 倒數,
// 空白鍵, 亂數, 提領, 自訂, 底線, 「」quotes, ...). MACHINE-CONSISTENT
// QUALITY, FLAGGED FOR NATIVE PASS (same convention as the other non-EN
// locales). House terms are identical to zh-Hans (格子/卡包/押注/獎池/...).
// royaleI18n.ts imports. Generated by the i18n parallel-work restructure so
// 8 agents can each own one segment file per locale without touching a
// shared file. This file should not need to change again: add new keys to
// the relevant segment file instead (core, board, cinema, arena, onboarding, docs, pages, chat, misc).
import core from "./core";
import board from "./board";
import cinema from "./cinema";
import arena from "./arena";
import onboarding from "./onboarding";
import docs from "./docs";
import pages from "./pages";
import chat from "./chat";
import misc from "./misc";

export const zhHant: Record<string, string> = {
  ...core,
  ...board,
  ...cinema,
  ...arena,
  ...onboarding,
  ...docs,
  ...pages,
  ...chat,
  ...misc,
};
